### ISSUE TITLE
<CR> not working

### ISSUE THREAD

**Issue by antistic** [tweekmonster/braceless.vim#29] opened 2016-04-05 21:42 UTC
Whenever I press `<CR>`, `braceless#python#override_cr()` gets pasted into my code over and over and over again until I press `<C-c>`. This is a bit unusable...

The first time this happened there was an error `clipboard: error: Error: target STRING not available`.

I am using neovim.

**Comment by tweekmonster** [comment] 2016-04-06 13:42
@notantonia Can you reproduce this reliably?  I'm unable to get the same results (I use Neovim as well).

**Comment by antistic** [comment] 2016-04-07 13:08
I went through my init.vim and it turns out that the problem only appears when using junegunn's [vim-peekaboo](https://github.com/junegunn/vim-peekaboo).

I've disabled it for now.

**Comment by tweekmonster** [comment] 2016-04-07 13:11
I see, thanks!  I don't use it, but I will to see if it can be fixed.  Could you give me steps to reproduce the issue?  Or is it as simple as opening peekaboo?

**Comment by tweekmonster** [comment] 2016-04-07 13:35
Never mind, I found the issue.  I'm using `imap` instead of `inoremap`.  I can't remember the reason I did this.  I'll fix it, but I have some local changes that I merged into master before I discovered some bugs that are breaking.  I need to address them before I push to Github.

**Closed as completed** 2016-04-07 14:19 UTC

**Comment by tweekmonster** [comment] 2016-04-07 15:38
@notantonia The issue should be gone now!
