### ISSUE TITLE
Add note re: `filetype indent off`?

### ISSUE THREAD

**Issue by beaugunderson** [tweekmonster/braceless.vim#16] opened 2016-02-25 21:15 UTC
I had to add `filetype indent off` to my Python-specific `.vimrc` file to get the braceless.vim indentation to work; maybe that should be added to the docs?

**Comment by tweekmonster** [comment] 2016-02-25 22:02
Hmm, could you tell me what `set indentexpr?` said before you fixed it yourself?  This plugin should be unaffected by that option since it's not loaded via indent.vim.  Running `:filetype` shows `filetype detection:ON  plugin:ON  indent:ON` for me.

**Comment by beaugunderson** [comment] 2016-02-25 23:01
ah interesting; I'll check indentexpr? shortly

---

**Comment by beaugunderson** [comment] 2016-02-26 06:04
when I have `filetype indent on` it gets set to: `GetPythonIndent(v:lnum)` which exists in `/usr/local/share/vim/vim74/indent/python.vim`.

I wonder if it's an ordering issue?

I execute `BracelessEnable +indent` from `~/.vim/after/ftplugin/python.vim`.

**Comment by tweekmonster** [comment] 2016-02-26 06:30
Oh okay I see what's going on now.  The way I intended this plugin to work was to let the builtin Python scripts load themselves while Braceless was lazy loaded with a FileType autocmd.  It was to avoid the need for a `indent/python.vim` script which would make this plugin opinionated.  In this case, the builtin `indent/python.vim` script is loaded after the ftplugin.

Could you try adding this to your `~/.vim/after/ftplugin/python.vim` script:

``` vim
let b:did_indent = 1
setlocal nolisp
setlocal autoindent
```

If that resolve it for you, I'll have this plugin set them when `+indent` is present.

**Comment by beaugunderson** [comment] 2016-02-26 06:35
adding that to my `~/.vim/after/ftplugin/python.vim` does not seem to have an effect (`indentexpr?` is still `GetPythonIndent(v:lnum)`)

**Comment by tweekmonster** [comment] 2016-02-26 07:02
Thanks for checking it out.  I'll take a closer look at this in the morning.

**Comment by beaugunderson** [comment] 2016-02-26 17:28
appreciate it! :)

**Comment by tweekmonster** [comment] 2016-02-29 16:08
@beaugunderson I wanted to tag this as `wontfix` with an explanation, but I looked at your dotfiles and see the value of what you're doing.  Now I want to adopt your layout to replace the trash heap that I'm using to configure Vim. :expressionless:

The problem is that `indent.vim` unsets `b:did_indent` and loads the filetype-specific indent script _after_ loading your ftplugin script.  The work around is to generate an `after/indent/python.vim` within the plugin's directory when Braceless is enabled to override the builtin indent script.  Since, a script is being generated, I want this to be an opt-in feature.  So, you'll need to at least add `let g:braceless_generate_scripts = 1` in your ftplugin script.

I'm not merging this into master yet since I wanted to see if you thought the updated doc explains this well enough.

**Comment by beaugunderson** [comment] 2016-03-02 04:29
@tweekmonster docs look good! hugely appreciate you supporting this workflow :)

**Closed as completed** 2016-03-02 07:37 UTC
